version: '3'
services:

  zookeeper:
    image: "confluentinc/cp-zookeeper:5.2.1"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
    networks:
      - proposta-net

  kafka:
    image: "confluentinc/cp-kafka:5.2.1"
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - proposta-net


  db_transacao:
    image: mysql:latest
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
      - 3307:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: transacao
      MYSQL_USER: romulo
      MYSQL_PASSWORD: romulo
      MYSQL_ROOT_PASSWORD: root
    networks:
      - proposta-net

  transacao:
    image: 'romulo/transacao'
    ports:
      - 8081:8080
    depends_on:
      - db_transacao
    environment:
      MYSQL_PASSWORD: romulo
      MYSQL_USER: romulo
      MYSQL_URL: jdbc:mysql://db_transacao:3307/transacao
    networks:
      - proposta-net



  transacoes:
    image: 'zupacademy/transacoes'
    ports:
      - 7777:7777
    depends_on:
      - kafka
    environment:
      SERVER_PORT: 7777
      LOG_LEVEL: INFO
      KAFKA_HOST: "kafka:29092"
    networks:
      - proposta-net

  vault:
    image: vault:1.5.3
    ports:
      - 8200:8200
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ee413645-dbe8-4848-afc6-6bb2768ada75
      VAULT_TOKEN: ee413645-dbe8-4848-afc6-6bb2768ada75
      VAULT_ADDR: http://127.0.0.1:8200

volumes:
  mysql-volume:


networks:
  proposta-net:
    driver: bridge